version: "3.8"

services:
  web:
    image: plataforma_educacional-web:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: plataforma_educacional
    volumes:
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - plataforma_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: plataforma_educacional
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - plataforma_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: senha123
    networks:
      - plataforma_network

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - plataforma_network

volumes:
  db_data:
  portainer_data:

networks:
  plataforma_network:
    driver: overlay
